### ISSUE TITLE
Feature Request - allow selection of report categories to run

### ISSUE THREAD

**Issue by andiih** [dima-horror/lighthouse.net#2]
Is it possible to provide support for --only-categories=performance|accessibility|best-practices|pwa|seo

At the moment I only want to run the performance reports, so this would speed things up a lot.

**Comment by dima-hx** [comment]
Hi!

Thanks for your help with code.

Now this feature is in master (https://github.com/dima-horror/lighthouse.net/pull/4) and available in Nuget as 1.0.4 version 

https://www.nuget.org/packages/lighthouse.net/

**Comment by andiih** [comment]
Many thanks. I couldn't figure out the trick for controling the serialisation of enums. Neat solution. Thanks.
