### ISSUE TITLE
Feature request - add possibility to add custom headers to run

### ISSUE THREAD

**Issue by alexdefine** [dima-horror/lighthouse.net#5]
In order to gather metrics for some of the pages I need to pre-setup additional headers (authorization, cookies, e.t.c). It shouldn't be too hard to implement, so I can do it by my self and create PR, just want to make sure this repo is still supported and my commit can be merged.

Regardless, thank you for creating this lib. I am looking forward to use it a lot in future for .net test automation projects.

**Comment by dima-hx** [comment]
Hi, @alexdefine !
Yep, this repo is still supported.
It will be great if you can do this.

Hello from Kiev :)

**Comment by dima-hx** [comment]
Hi, @alexdefine.

Any updates?

**Comment by alexdefine** [comment]
Hello @dima-horror, I have this feature ready on my fork for some time, were too busy to wrap it up and create PR. Hopefully will do it on this weekends.

**Comment by dima-hx** [comment]
Closed due to inactivity
