### ISSUE TITLE
Setting EmulatedFormFactor does not return any results

### ISSUE THREAD

**Issue by mmanshad** [dima-horror/lighthouse.net#7]
Calling the following method never completes the async Task. However, if I remove "_EmulatedFormFactor=FormFactor.Mobile_" property from the **AuditRequest** everything seems to work. Any ideas? I am wanting to look at Desktop vs. Mobile metrics. 
  
              static async Task GetLightHouseValsAsync(string url, FormFactor form)
              {
                  try
                  {
                      var lh = new Lighthouse();
      
                      var ar = new AuditRequest(@url)
                      {
                          OnlyCategories = new[]
                          {
                              lighthouse.net.Objects.Category.SEO,
                              lighthouse.net.Objects.Category.Performance,
                              lighthouse.net.Objects.Category.Accessibility,
                              lighthouse.net.Objects.Category.BestPractices,
                              lighthouse.net.Objects.Category.PWA,
                          },
                          EmulatedFormFactor=FormFactor.Mobile,
                          EnableLogging = false,
                      };
                      var res = await lh.Run(ar);
      
                      if (res != null)
                      {
                          Console.WriteLine("Performance: " + (res.Performance * 100) + "%");
                          Console.WriteLine("Accessibility: " + (res.Accessibility * 100) + "%");
                          Console.WriteLine("BestPractices: " + (res.BestPractices * 100) + "%");
                          Console.WriteLine("PWA: " + (res.Pwa * 100) + "%");
                          Console.WriteLine("SEO: " + (res.Seo * 100) + "%");
                      }
                      else
                      {
                          Console.WriteLine("No LightHouse Data!");
                      }
                  }
                  catch(Exception ex)
                  {
                      Console.WriteLine(ex.Message);
                  }
              }

**Comment by dima-hx** [comment]
Good day, @mmanshad .

Your example in .net framework tests works properly.

![2021-05-21_16h41_39](https://user-images.githubusercontent.com/13537063/119146615-7a30c300-ba53-11eb-9c7d-c53e1208a4ac.png)

Is `FormFactor` your own enum? It should be reference in class `AuditRequest` , e.g `AuditRequest.FormFactor.Mobile`

**Comment by mmanshad** [comment]
Thanks for the response @dima-horror 

I am using **AuditRequest.FormFactor.Mobile**  (See below) as I am only interested in Mobile form factor, however, method call never returns. Only when I remove setting the **EmulateFormFactor** property from the AuditRequest object, the method call returns. I am using  _version 1.0.5_ of the _LightHouse.net_ package on _targetFramework=net461_ and _Google NPM Lighthouse package_ _version 7.5.0_

![image](https://user-images.githubusercontent.com/14350941/119210127-e61d2680-ba67-11eb-95d7-028a14a5437d.png)

**Comment by Algus88** [comment]
Hi, @dima-horror . I have the same issue when I add FormFactor property to AuditRequest constructor I got an infinity running test. I have used default example just change FormFactor property.  Target framework  net48
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="lighthouse.net" version="1.0.5" targetFramework="net48" />
  <package id="MSTest.TestAdapter" version="2.2.7" targetFramework="net48" />
  <package id="MSTest.TestFramework" version="2.2.7" targetFramework="net48" />
  <package id="Newtonsoft.Json" version="11.0.2" targetFramework="net48" />
</packages>
```

```
using System;
using System.Threading.Tasks;
using lighthouse.net.Objects;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using static lighthouse.net.Objects.AuditRequest;

namespace lighthouse.net.tests
{
    [TestClass]
    public class NpmTests
    {
        [TestMethod]
        public async Task FormFactorTest()
        {
            var lh = new Lighthouse();
            var ar = new AuditRequest("http://example.com")
            {
                EmulatedFormFactor = FormFactor.Desktop
            };

            var res = await lh.Run(ar);

            Assert.IsNotNull(res);
        }
    }
}
```

**Comment by dima-hx** [comment]
Hi, @Algus88 , @mmanshad . 
Yep, I figure out the reason, why FormFactor was not working. From lighthouse package 7.0 and higher there was [some changes in the input parameters.](https://github.com/GoogleChrome/lighthouse/blob/master/docs/emulation.md)

I fixed it on https://github.com/dima-horror/lighthouse.net/pull/10

New version 1.0.6 with this fix is now available on [nuget](https://www.nuget.org/packages/lighthouse.net/1.0.6).
