### ISSUE TITLE
Using Lighthouse v8.0.0 causes crash

### ISSUE THREAD

**Issue by xithalius** [dima-horror/lighthouse.net#9]
Using a slightly adjusted version of the basic example from the readme causes a crash due to an unhandled exception when using Lighthouse v8.0.0. Downgrading Lighthouse to v7.5.0 resolves this issue.

`An unhandled exception has occurred while executing the request.`
`System.Exception: (node:12080) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead(Use 'node --trace-deprecation ...' to show where the warning was created)`

I'm not using the LTS version of Node.

**Comment by dima-hx** [comment]
@xithalius , the problem is gone?
